import{a as S,S as v,i as n}from"./assets/vendor-BkC4bTqC.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const P="54847026-fc22f2464403aa7b57f5b9274",q="https://pixabay.com/api/";async function d(r){const t={key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0};try{return(await S.get(q,{params:t})).data}catch(s){throw console.error("Info about error",s),s}}const m=document.querySelector(".gallery"),u=document.querySelector(".loader"),y=document.querySelector("#load-btn");let B=new v(".gallery a",{captionsData:"alt",captionDelay:250});async function g(r){const t=r.map(({webformatURL:s,largeImageURL:a,tags:e,likes:o,views:c,comments:L,downloads:w})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${a}">
          <img class="gallery-image" src="${s}" alt="${e}" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> ${o}</p>
          <p class="info-item"><b>Views</b> ${c}</p>
          <p class="info-item"><b>Comments</b> ${L}</p>
          <p class="info-item"><b>Downloads</b> ${w}</p>
        </div>
      </li>`).join("");m.insertAdjacentHTML("beforeend",t),B.refresh()}function $(){m.innerHTML=""}function h(){u&&u.classList.add("is-open")}function p(){u&&u.classList.remove("is-open")}function b(){y.classList.add("is-open")}function f(){y.classList.remove("is-open")}const E=document.querySelector("#load-btn"),M=document.querySelector(".form");let l="",i=1;E.addEventListener("click",async()=>{f(),h();try{i+=1;const r=await d(l,i);g(r.hits);const s=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"});const a=Math.ceil(r.totalHits/15);i>=a?(f(),n.info({message:"We're sorry, but you've reached the end of search results."})):b()}catch(r){n.error({message:"Error fetching images!"}),console.log(r)}finally{p()}});M.addEventListener("submit",async r=>{if(r.preventDefault(),l=r.currentTarget.elements["search-text"].value.trim(),!l){n.warning({message:"Search field cannot be empty!"});return}i=1,$(),f(),h();try{const t=await d(l,i);if(t.hits.length===0)n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});else{g(t.hits);const s=Math.ceil(t.totalHits/15);i<s?b():n.info({message:"We're sorry, but you've reached the end of search results."})}}catch(t){console.log(t),n.error({message:"Something went wrong. Please try again."})}finally{p(),r.target.reset()}});
//# sourceMappingURL=index.js.map
